//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.17 at 01:30:38 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://nl/harmster/webservices/accountservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package nl.harmster.webservices.accountservice;
